language: node_js
node_js:
  - "stable"
install:
  - npm i webpack-cli
  - npm i webpack
  - npm install

before_script:
  - ls -la node_modules

jobs:
  include:
    - script: npm build
