language: node_js
node_js:
  - "stable"
install:
  - npm i -g yarn && yarn
  - npm i webpack-cli
  - npm i webpack
  - npm install
  - npm i react
  - ls -la node_modules
before_script:
  - yarn prod
